###
# Test your FastAPI endpoints
###

GET http://127.0.0.1:8000/stocks/23
Accept: application/json

###

GET http://127.0.0.1:8000/healthcheck
Accept: application/json

###

POST http://127.0.0.1:8000/stocks
Content-Type: application/json

{
  "name": "sk텔레콤",
  "code": "017670",
  "market_id": 1
}

###


